- src/main/kotlin/com/umjari/server/domain/group/dto/GroupDto.kt
- src/main/kotlin/com/umjari/server/domain/group/exception/GroupIdNotFoundException.kt
- src/main/kotlin/com/umjari/server/domain/group/service/GroupService.kt
- src/main/kotlin/com/umjari/server/global/config/SecurityConfig.kt
- src/main/kotlin/com/umjari/server/global/exception/CustomException.kt
- src/main/kotlin/com/umjari/server/global/exception/CustomNotValidExceptionControllerAdvice.kt
- src/main/kotlin/com/umjari/server/global/exception/ErrorResponse.kt
- src/main/kotlin/com/umjari/server/global/exception/ErrorType.kt
- src/main/kotlin/com/umjari/server/global/exception/ExceptionControllerAdvice.kt
Exception Handling and Resolving custom exception response.
> feat: custom exception and validation exception handling

- src/main/kotlin/com/umjari/server/domain/group/controller/GroupController.kt
- src/main/kotlin/com/umjari/server/domain/group/dto/GroupDto.kt
- src/main/kotlin/com/umjari/server/domain/group/service/GroupService.kt
- src/main/kotlin/com/umjari/server/global/config/SecurityConfig.kt
Separate group recruit status modify endpoint from group modify endpoint
> feat: divide partial group update api

- src/main/resources/application-docker.yml
- src/main/resources/application-local.yml
- src/main/resources/application.yml
- src/test/kotlin/com/umjari/server/UmjariApplicationTests.kt
- src/test/resources/application.yml
> feat: profile refactoring

- src/main/kotlin/com/umjari/server/domain/concert/controller/ConcertController.kt
- src/main/kotlin/com/umjari/server/domain/concert/dto/ConcertDto.kt
- src/main/kotlin/com/umjari/server/domain/concert/service/ConcertService.kt
- src/main/kotlin/com/umjari/server/domain/group/service/GroupService.kt
- src/main/kotlin/com/umjari/server/domain/region/service/RegionService.kt
- src/main/kotlin/com/umjari/server/global/config/SecurityConfig.kt
Implement
`PUT /api/v1/concert/{concert_id}/details/` : Update concert details
`PUT /api/v1/concert/{concert_id}/info/` : Update concert information
Resolves #11
> feat: divide concert update api into two parts

- src/main/kotlin/com/umjari/server/domain/concert/service/ConcertService.kt
- src/test/kotlin/com/umjari/server/domain/concert/ConcertTests.kt
- src/test/kotlin/com/umjari/server/domain/group/GroupTests.kt
Unit test for concert domain
Resolves #10
> test: group domain test

- src/main/kotlin/com/umjari/server/domain/auth/model/UserPrincipal.kt
- src/main/kotlin/com/umjari/server/domain/user/model/User.kt
- src/main/kotlin/com/umjari/server/global/config/SecurityConfig.kt
- src/test/kotlin/com/umjari/server/domain/concert/ConcertTests.kt
- src/test/kotlin/com/umjari/server/domain/group/GroupTests.kt
- src/test/kotlin/com/umjari/server/utils/TestUtils.kt
divide  securityConfig into ROLE_USER, ROLE_ADMIN api
Resolves #15
> nemga123/add admin role/15

- src/main/kotlin/com/umjari/server/domain/group/controller/GroupController.kt
- src/main/kotlin/com/umjari/server/domain/group/dto/GroupRegisterDto.kt
- src/main/kotlin/com/umjari/server/domain/group/model/GroupMember.kt
- src/main/kotlin/com/umjari/server/domain/group/repository/GroupMemberRepository.kt
- src/main/kotlin/com/umjari/server/domain/group/service/GroupService.kt
- src/main/kotlin/com/umjari/server/domain/user/repository/UserRepository.kt
- src/main/kotlin/com/umjari/server/global/config/SecurityConfig.kt
- src/test/kotlin/com/umjari/server/domain/group/GroupTests.kt
Api for enroll group member by user id list
Resolves #17
> feat: register group member

- src/main/kotlin/com/umjari/server/global/config/SwaggerConfig.kt
Add authorization config in swagger for authentication APIs
> feat: swagger authorization

- src/main/kotlin/com/umjari/server/domain/groupqna/exception/QnaCannotBeUpdatedException.kt
- src/main/kotlin/com/umjari/server/domain/groupqna/model/GroupQnaReply.kt
- src/main/kotlin/com/umjari/server/domain/groupqna/repository/GroupQnaReplyRepository.kt
- src/main/kotlin/com/umjari/server/domain/groupqna/service/GroupQnaService.kt
- src/main/kotlin/com/umjari/server/global/exception/ErrorType.kt
> feat: ktlint

- build.gradle.kts
- src/main/kotlin/com/umjari/server/domain/groupqna/controller/GroupQnaController.kt
- src/main/kotlin/com/umjari/server/domain/groupqna/dto/GroupQnaDto.kt
- src/main/kotlin/com/umjari/server/domain/groupqna/dto/GroupQnaReplyDto.kt
- src/main/kotlin/com/umjari/server/domain/groupqna/model/GroupQna.kt
- src/main/kotlin/com/umjari/server/domain/groupqna/model/GroupQnaReply.kt
- src/main/kotlin/com/umjari/server/domain/groupqna/repository/GroupQnaReplyRepository.kt
- src/main/kotlin/com/umjari/server/domain/groupqna/repository/GroupQnaRepository.kt
- src/main/kotlin/com/umjari/server/domain/groupqna/service/GroupQnaReplyService.kt
- src/main/kotlin/com/umjari/server/domain/groupqna/service/GroupQnaService.kt
- src/main/kotlin/com/umjari/server/global/config/SecurityConfig.kt
group qna reply domain api
Resolves #25
> nemga123/group qna reply/25

- src/main/kotlin/com/umjari/server/domain/group/controller/GroupController.kt
- src/main/kotlin/com/umjari/server/domain/group/service/GroupService.kt
- src/main/kotlin/com/umjari/server/global/config/SecurityConfig.kt
Implement group register as admin role api 
Resolves #33
> feat: implement group admin register api

- src/main/kotlin/com/umjari/server/domain/concert/controller/ConcertController.kt
- src/main/kotlin/com/umjari/server/domain/concert/repository/ConcertRepository.kt
- src/main/kotlin/com/umjari/server/domain/concert/service/ConcertService.kt
- src/main/kotlin/com/umjari/server/domain/concert/specification/ConcertSpecification.kt
- src/main/kotlin/com/umjari/server/domain/user/service/UserService.kt
- src/main/kotlin/com/umjari/server/global/config/SecurityConfig.kt
Filtering concert lists by concert dashboard api
`GET /api/v1/concert/dashboard/`
Resolves #36
> feat: dashboard api of concert with filter

- src/main/kotlin/com/umjari/server/domain/auth/dto/AuthDto.kt
- src/main/kotlin/com/umjari/server/domain/auth/service/AuthService.kt
- src/main/kotlin/com/umjari/server/domain/groupqna/controller/GroupQnaController.kt
- src/main/kotlin/com/umjari/server/domain/groupqna/dto/GroupQnaDto.kt
- src/main/kotlin/com/umjari/server/domain/groupqna/dto/GroupQnaReplyDto.kt
- src/main/kotlin/com/umjari/server/domain/groupqna/service/GroupQnaService.kt
- src/main/kotlin/com/umjari/server/domain/user/dto/UserDto.kt
- src/main/kotlin/com/umjari/server/domain/user/model/User.kt
- src/test/kotlin/com/umjari/server/utils/TestUtils.kt
Add name column in user model.
Resolves #30
> feat: add name field on user model & modify response of qna user

- scripts/start.sh
- src/main/resources/application.yml
Modify deploy scripts that add s3 configurations.
> fix: deploy shell scripts

- src/main/kotlin/com/umjari/server/domain/concert/service/ConcertService.kt
- src/main/resources/templates/verifyEmail.html
> fix: concert dashboard query ignore cases

- src/main/kotlin/com/umjari/server/domain/auth/dto/AuthDto.kt
- src/main/kotlin/com/umjari/server/domain/auth/dto/UserDto.kt
- src/main/kotlin/com/umjari/server/domain/auth/service/AuthService.kt
- src/main/kotlin/com/umjari/server/domain/user/model/User.kt
- src/test/kotlin/com/umjari/server/utils/TestUtils.kt
Remove unnecessary phone number field.
Resolves #52
> fix: remove unnecessary phone number field.

- src/main/kotlin/com/umjari/server/domain/auth/service/AuthService.kt
- src/main/kotlin/com/umjari/server/domain/mailverification/repository/VerifyTokenRepository.kt
When multiple verification tokens in db, raise error because service get only on of them. So modify to get the most recent token.
Resolves #55
> fix: verification token order

- src/main/kotlin/com/umjari/server/global/config/CorsConfig.kt
> ktlint format

- src/main/kotlin/com/umjari/server/global/config/CorsConfig.kt
> fix: cors config

- src/main/kotlin/com/umjari/server/domain/group/controller/GroupController.kt
- src/main/kotlin/com/umjari/server/domain/group/dto/GroupDto.kt
- src/main/kotlin/com/umjari/server/domain/group/service/GroupService.kt
add member type field in retrieve group api
Resolves #62
> feat: add member type field in retrieve group api

- src/main/kotlin/com/umjari/server/global/pagination/PageResponse.kt
- src/main/resources/application.yml
One-based index pagination, not zero-based for frontend.
Resolves #66
> feat: one based index pagination

- src/main/kotlin/com/umjari/server/domain/concert/dto/ConcertDto.kt
- src/main/kotlin/com/umjari/server/domain/group/repository/GroupMemberRepository.kt
- src/main/kotlin/com/umjari/server/domain/group/service/GroupService.kt
- src/main/kotlin/com/umjari/server/domain/user/model/User.kt
- src/main/kotlin/com/umjari/server/domain/user/repository/UserRepository.kt
- src/test/kotlin/com/umjari/server/domain/concert/ConcertTests.kt
- src/test/kotlin/com/umjari/server/domain/group/GroupTests.kt
- src/test/kotlin/com/umjari/server/domain/user/UserTests.kt
- src/test/kotlin/com/umjari/server/global/auth/AuthTests.kt
- src/test/kotlin/com/umjari/server/utils/TestUtils.kt
enhance test and resolve bug in group member register sql.
> resolve bug in group member register.

- src/main/kotlin/com/umjari/server/domain/auth/dto/AuthDto.kt
- src/main/kotlin/com/umjari/server/domain/auth/service/AuthService.kt
- src/main/kotlin/com/umjari/server/domain/groupqna/dto/GroupQnaDto.kt
- src/main/kotlin/com/umjari/server/domain/groupqna/repository/GroupQnaRepository.kt
- src/main/kotlin/com/umjari/server/domain/user/dto/UserDto.kt
- src/main/kotlin/com/umjari/server/domain/user/model/User.kt
Add profile image field and time stamp field in qna response.
Resolves #69
> feat: add profile image field and timestamp field

- src/main/kotlin/com/umjari/server/domain/image/model/Image.kt
- src/main/kotlin/com/umjari/server/domain/image/service/ImageService.kt
- src/main/kotlin/com/umjari/server/domain/user/controller/UserController.kt
- src/main/kotlin/com/umjari/server/domain/user/dto/UserDto.kt
- src/main/kotlin/com/umjari/server/domain/user/service/UserService.kt
Implement api that update user profile image.
Resolves #71
> feat: update user profile image

- src/main/kotlin/com/umjari/server/domain/groupqna/controller/GroupQnaController.kt
- src/main/kotlin/com/umjari/server/domain/groupqna/dto/GroupQnaDto.kt
- src/main/kotlin/com/umjari/server/domain/groupqna/dto/GroupQnaReplyDto.kt
- src/main/kotlin/com/umjari/server/domain/groupqna/service/GroupQnaService.kt
add boolean field that current user is author of article
Resolves #79
> feat: add boolean field that current user is author of article

- src/main/kotlin/com/umjari/server/domain/auth/dto/AuthDto.kt
- src/main/kotlin/com/umjari/server/global/validation/KeyWordsBlock.kt
- src/main/kotlin/com/umjari/server/global/validation/KeyWordsBlockValidator.kt
- src/test/kotlin/com/umjari/server/utils/TestUtils.kt
Block key words `admin`, `umjari`, `관리자`, in user information.
Resolves #77
> feat: block key words in user info

- src/main/kotlin/com/umjari/server/domain/groupqna/dto/GroupQnaReplyDto.kt
Modify qna reply response to return with `authorInfo` and `isAuthor` field.
Resolves #79
> fix: qna reply response fix.

- src/main/kotlin/com/umjari/server/UmjariApplication.kt
Set Seoul Timezone when start server.
> fix: time zone config

- src/main/kotlin/com/umjari/server/domain/groupqna/repository/GroupQnaRepository.kt
Fix jpql field error in qna text search.
Resolves #87
> fix: jpql error in get qna by text search

- src/main/resources/application.yml
Add max file size limit in cofig 10MB.
Resolves #91
> fix: max file size and request size in config

- src/main/kotlin/com/umjari/server/domain/user/dto/UserDto.kt
Return nickname with user mypage info api.
Resolves #97
> fix: return nickname with user info

- src/main/kotlin/com/umjari/server/domain/auth/JwtTokenProvider.kt
- src/main/kotlin/com/umjari/server/global/auth/filter/CustomUsernamePasswordAuthenticationFilter.kt
add user profile name in login success response
Resolves #109
> feat: add user profile name in login success response

- src/main/kotlin/com/umjari/server/domain/concert/controller/ConcertMusicController.kt
- src/main/kotlin/com/umjari/server/domain/concert/dto/ConcertParticipantDto.kt
- src/main/kotlin/com/umjari/server/domain/concert/service/ConcertMusicService.kt
- src/test/kotlin/com/umjari/server/domain/concert/ConcertTests.kt
Simplify participant list in get concertMusic request.
> feat: simplify response of participant list

- src/main/kotlin/com/umjari/server/domain/concert/service/ConcertService.kt
group role check before update concert set list
> fix: group role check before update concert set list

- src/main/kotlin/com/umjari/server/domain/group/service/GroupMemberAuthorityService.kt
- src/main/kotlin/com/umjari/server/domain/user/repository/UserRepository.kt
- src/test/kotlin/com/umjari/server/domain/concert/ConcertTests.kt
Allow all api to admin user.
Resolves #122
> feat: allow all api to admin user

- src/main/kotlin/com/umjari/server/domain/concert/dto/ConcertParticipantDto.kt
- src/main/kotlin/com/umjari/server/domain/concert/repository/ConcertParticipantRepository.kt
modify response field joined concert api
> feat: modify response field joined concert api

- src/main/kotlin/com/umjari/server/domain/concert/dto/ConcertParticipantDto.kt
- src/main/kotlin/com/umjari/server/domain/concert/repository/ConcertParticipantRepository.kt
modify response field joined concert list api
> feat: modify response field joined concert list api

- src/main/kotlin/com/umjari/server/domain/concert/model/ConcertMusic.kt
- src/main/kotlin/com/umjari/server/domain/concert/repository/ConcertMusicRepository.kt
- src/main/kotlin/com/umjari/server/domain/concert/service/ConcertService.kt
replace all set list when update request
Resolves #135
> fix: replace all set list when update request

- src/main/kotlin/com/umjari/server/domain/group/controller/GroupController.kt
Set smaller page size to ten on get concerts api.
Resolves #142
> fix: set page size to 10

- src/main/kotlin/com/umjari/server/domain/post/dto/CommunityPostDto.kt
delete duplicated board name field.
Resolves #151
> feat: get all post list of all board

- src/main/kotlin/com/umjari/server/domain/music/controller/MusicController.kt
- src/main/kotlin/com/umjari/server/domain/music/repository/MusicRepository.kt
- src/main/kotlin/com/umjari/server/domain/music/service/MusicService.kt
intergrate music text search cross search to language.
Resolves #162
> feat: intergrate music text search

- src/main/kotlin/com/umjari/server/domain/concert/controller/ConcertMusicController.kt
- src/main/kotlin/com/umjari/server/domain/concert/dto/ConcertParticipantDto.kt
- src/main/kotlin/com/umjari/server/domain/concert/service/ConcertMusicService.kt
- src/test/kotlin/com/umjari/server/domain/concert/ConcertTests.kt
When deleting participant list, return failed user.
Resolves #164
> feat: return failed user when deleting concert participants

- src/main/kotlin/com/umjari/server/domain/music/repository/MusicRepository.kt
Fix get music query predicate.
Resolves #166
> fix: get music query fix

- src/main/kotlin/com/umjari/server/domain/group/model/Group.kt
set recruit detail field to textfield.
> hotfix: set recruit detail field to textfield

- src/main/kotlin/com/umjari/server/domain/image/model/Image.kt
- src/main/kotlin/com/umjari/server/domain/image/model/ImageEntityListener.kt
- src/main/kotlin/com/umjari/server/domain/image/service/ImageService.kt
- src/main/kotlin/com/umjari/server/domain/image/service/S3Service.kt
- src/test/kotlin/com/umjari/server/domain/album/AlbumTests.kt
> hotfix: image url by user pk

- src/main/kotlin/com/umjari/server/domain/friend/repository/FriendRepository.kt
Get friend list sql bugs.
Resolves #186
> fix: friends list sql error

- src/main/kotlin/com/umjari/server/domain/group/dto/GroupDto.kt
- src/main/kotlin/com/umjari/server/domain/group/repository/GroupRepository.kt
- src/main/kotlin/com/umjari/server/domain/group/service/GroupService.kt
Add set list in get group detail response
Resolves #197
> fix: add set list in get group detail response

- src/main/kotlin/com/umjari/server/domain/group/controller/GroupController.kt
- src/main/kotlin/com/umjari/server/domain/group/dto/GroupDto.kt
- src/main/kotlin/com/umjari/server/domain/group/repository/GroupMemberRepository.kt
- src/main/kotlin/com/umjari/server/domain/group/repository/GroupMusicRepository.kt
- src/main/kotlin/com/umjari/server/domain/group/service/GroupService.kt
- src/test/kotlin/com/umjari/server/domain/group/GroupTests.kt
Add friend member count in group search response.
Resolves #202
> feat: add friend count in group search api

- src/main/kotlin/com/umjari/server/domain/concert/service/ConcertMusicService.kt
- src/main/kotlin/com/umjari/server/domain/group/group/controller/GroupController.kt
- src/main/kotlin/com/umjari/server/domain/group/group/service/GroupService.kt
- src/main/kotlin/com/umjari/server/domain/user/repository/UserRepository.kt
- src/main/kotlin/com/umjari/server/domain/user/service/UserService.kt
- src/main/kotlin/com/umjari/server/global/config/SecurityConfig.kt
- src/test/kotlin/com/umjari/server/domain/group/GroupTests.kt
implement group member deletion
Resolves #211
> feat: implement group member deletion

- src/main/kotlin/com/umjari/server/domain/user/model/User.kt
> hotfix: interest music regex typo

- src/main/kotlin/com/umjari/server/domain/user/service/UserService.kt
> hotfix: region update error

- build.gradle.kts
- src/main/kotlin/com/umjari/server/global/config/SecurityConfig.kt
- src/main/resources/application.yml
feat: prometheus and grafana setting
Resolves #232
> feat: prometheus and grafana setting

- src/main/kotlin/com/umjari/server/domain/group/group/model/Group.kt
hotfix: concert setlist order fix
> hotfix: concert setlist order fix

- src/main/kotlin/com/umjari/server/domain/concert/service/ConcertCommentService.kt
수정 사항에 관한 간단한 요약을 작성해주세요.
Resolves #<issue No.>
> fix delete concert comment function args

- src/main/kotlin/com/umjari/server/domain/concert/service/ConcertCommentService.kt
수정 사항에 관한 간단한 요약을 작성해주세요.
Resolves #<issue No.>
> hotfix : delete concert comment repo

- src/main/kotlin/com/umjari/server/domain/concert/repository/ConcertCommentRepository.kt
수정 사항에 관한 간단한 요약을 작성해주세요.
Resolves #<issue No.>
> hotfix : return type
